######## Start builder #######
FROM ubuntu:20.04

USER root

# Required so that pipes work properly in the Dockerfile
SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

# Package installations
RUN apt-get update && \
    apt-get install -y \
    # The following only used for testing the inside the run environment
    ack-grep \
    vim \
    # Required by OpenPegasus both in build and server run
    libssl-dev \
    libpam0g-dev \
    && apt-get remove -y perl

# Pegasus root directory.  The OpenPegasus git repository and home where
# results of build are saved is within this directory. These env vars are
# consistent for all OpenPegasus builds
# TODO: I think these should come from the builder build and not be repeated
#       here.  Or maybe just from here but not both
ENV BUILDDIR=builddir
ENV PEGASUS_BUILD_ROOT=/root/${BUILDDIR}
ENV PEGASUS_HOME=${PEGASUS_BUILD_ROOT}/openpegasus_home

# Create the home directory
RUN mkdir -p ${PEGASUS_HOME}

# Run settings
#
# Settings below that are flags, with values set to true, enable the action
# simply through the existence of the variable.  The variables value has no
# effect.  Note that there are almost NO environment variables to control
# pegasus execution.  Execution variations are controlled through the
# config variables that can be viewed through the client cimconfig
# and the web admin interface
ENV PATH=${PEGASUS_HOME}/bin:$PATH
ENV LD_LIBRARY_PATH=${PEGASUS_HOME}/bin:${LD_LIBRARY_PATH}

# Add makefile for using this build image
#TODO: Not sure this does anything
COPY ./openpegasus_home ${PEGASUS_HOME}


# Build folder
WORKDIR ${PEGASUS_BUILD_ROOT}

# Build the binaries and run the cimserver
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["cimserver; tail -f /dev/null"]
