######## Start builder #######
FROM ubuntu:20.04

USER root

# Required so that pipes work properly in the Dockerfile
SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

# Package installations in stallions for the run package
RUN apt-get update && \
    apt-get install -y  --no-install-recommends \
    openssl \
    && apt-get remove -y perl

# Pegasus directories.  The OpenPegasus run directory is the single directory
# that will contain the lib and bin directories of the OpenPegasus runtime
# in the run image. This is taken from the
ENV PEGASUS_RUN_ROOT=${"/root/pegasus_home"}

# Define the OpenPegasus  run settings. These are minimal.

# Add OpenPegasus bin directory to PATH to get access to runtime components
ENV PATH=$PATH:${PEGASUS_RUN_ROOT}/bin

# Add the OpenPegasus library to the LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=${PEGASUS_RUN_ROOT}/lib:${LD_LIBRARY_PATH}

# TODO: Does this have to be part of the run time environment???
ENV PEGASUS_HAS_SSL=true

# Add the pegasus build results to the run image root directory
COPY ./openpegasus_home ${PEGASUS_RUN_ROOT}
# Copy the build environment variables as record of the build configuration
COPY ./pegasus-build-variables.env ${PEGASUS_RUN_ROOT}

# Pegasus Run components directory. This directory contains the bin, lib,
# repository, , Revocation list, and trace directories and the certificates.
#
WORKDIR ${PEGASUS_RUN_ROOT}

# Set to start server on startup. Can override on command line run command
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["cimserver; tail -f /dev/null"]
