######## Start builder #######
FROM ubuntu:20.04

USER root

# Required so that pipes work properly in the Dockerfile
SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

# Package installations in stallions for the run package
RUN apt-get update && \
    apt-get install -y  --no-install-recommends \
    openssl \
    && apt-get remove -y perl

# Pegasus directories.  The OpenPegasus git repository and home where
# results of build are saved is within this directory. These env vars are
# consistent for all OpenPegasus builds
# TODO: I think these should come from the builder docker and not be repeated
#       here.  Or maybe just from here but not both
ENV BUILDDIR=builddir
ENV PEGASUS_BUILD_ROOT=/root/${BUILDDIR}
ENV PEGASUS_HOME=${PEGASUS_HOME}

# Create the home directory which will contain the Pegasus runtime during
# the build
RUN mkdir -p ${PEGASUS_HOME}

# Define the build settings
#
# Settings below that are flags, with values set to true, enable the action
# simply through the existence of the variable.  The variables value has no
# effect.  Note that there are almost NO environment variables to control
# pegasus execution.  Execution variations are controlled through the
# config variables that can be viewed through the client cimconfig
# and the web admin interface

# ADD OpenPegasus bin directory to PATH to get access to runtime components
ENV PATH=$PATH:${PEGASUS_HOME}/bin

# Add the OpenPegasus library to the LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=${PEGASUS_HOME}/lib:${LD_LIBRARY_PATH}

# TODO: Does this have to be part of the run time environment???
ENV PEGASUS_HAS_SSL=true

# OpenPegasus make target to execute post build tests. Can be any of the
# targets defined in OpenPegasus Makefile or TestMakefile
ENV PEGASUS_TEST_TARGET=alltests

# add the pegasus build results to the run image
COPY ./openpegasus_home ${PEGASUS_HOME}

# Build folder
WORKDIR ${PEGASUS_BUILD_ROOT}

# Build the binaries and run the cimserver
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ["cimserver; tail -f /dev/null"]
